sonar.projectKey=forme-user-service
sonar.projectName=ForME User Service
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
sonar.exclusions=target/**,**/target/**,**/*.class
sonar.test.inclusions=src/test/java/**/*.java
