sonar.projectKey=forme-frontend-auth-dashboard
sonar.projectName=ForME Frontend Auth and Dashboard
sonar.projectVersion=1.0

sonar.sources=src/app/features/auth,src/app/admin/pages/dashboard,src/app/features/formation/services/statistics.service.ts
sonar.tests=src/app/features/auth,src/app/admin/pages/dashboard,src/app/features/formation/services
sonar.test.inclusions=src/app/features/auth/**/*.spec.ts,src/app/admin/pages/dashboard/**/*.spec.ts,src/app/features/formation/services/statistics.service.spec.ts
sonar.exclusions=**/*.spec.ts,dist/**,node_modules/**,coverage/**
sonar.typescript.lcov.reportPaths=coverage/forme-frontend/lcov.info

sonar.sourceEncoding=UTF-8
